language: php

matrix:
  include:
    - env: DBTYPE=mysql; MW=master
      php: 7.1
    - env: DBTYPE=mysql; MW=1.28.0
      php: 5.5
    - env: DBTYPE=sqlite; MW=1.31.3
      php: 7.0
    - env: DBTYPE=mysql; MW=1.32.3; TYPE=coverage
      php: 7.1

install: travis_retry composer self-update

before_script: bash ./build/travis/before_script.sh

script: bash ./build/travis/script.sh

after_success: bash ./build/travis/after_success.sh
