language: php

env:
  - THENEEDFORTHIS=FAIL

matrix:
  include:
    - env: DBTYPE=mysql;MW=master
      php: 5.3
    - env: DBTYPE=sqlite;MW=1.19
      php: 5.4
    - env: DBTYPE=mysql;MW=1.20
      php: 5.5
    - env: DBTYPE=sqlite;MW=1.21
      php: 5.3
  exclude:
    - env: THENEEDFORTHIS=FAIL

before_script: bash .travis.sh

script:
  - cd ../phase3/extensions/SubPageList ; phpunit

notifications:
  email:
    recipients:
      - jeroendedauw@gmail.com
    on_success: change
    on_failure: always