language: php

env:
  - THENEEDFORTHIS=FAIL

matrix:
  include:
    - env: DBTYPE=mysql; MW=master
      php: 5.3
    - env: DBTYPE=sqlite; MW=1.19.0
      php: 5.4
    - env: DBTYPE=mysql; MW=1.20.0
      php: 5.5
    - env: DBTYPE=sqlite; MW=1.21.0
      php: 5.3
  exclude:
    - env: THENEEDFORTHIS=FAIL

before_script: bash .travis.sh

script:
  - cd ../phase3/extensions/SubPageList ; phpunit --coverage-clover build/logs/clover.xml

after_success:
  - php vendor/bin/coveralls -v

notifications:
  email:
    recipients:
      - jeroendedauw@gmail.com
    on_success: change
    on_failure: always